version: 2.1
jobs:
  build:
    working_directory: /home/node/app
    docker:
      - image: node:10.16.0
        environment:
          NODE_ENV: development
          MONGO_URI: mongodb://localhost:27017/crowi
          REDIS_URL: redis://localhost:6379/crowi
          ELASTICSEARCH_URI: //localhost:9200/
          PLANTUML_URI: //localhost:8080
          FILE_UPLOAD: local
          MONGOMS_DOWNLOAD_MIRROR: https://downloads.mongodb.org
      - image: mongo:3.6.13
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - restore_cache:
          keys:
            - node_modules_{{ checksum "package-lock.json" }}
            - mongo_binaries_{{ checksum "test/mongo-environment.js" }}
      - run: npm install
      - save_cache:
          key: node_modules_{{ checksum "package-lock.json" }}
          paths:
            - /home/node/app/node_modules
      - run: npm run type-check
      - run: npm run lint
      - run: npm run build
      - run: npm run coverage
      - codecov/upload:
          file: ./coverage/
          when: on_success
      - save_cache:
          key: mongo_binaries_{{ checksum "test/mongo-environment.js" }}
          paths:
            - /root/.mongo-binaries
workflows:
  version: 2
  main:
    jobs:
      - build
orbs:
  codecov: codecov/codecov@1.0.5
